version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: bizflow-postgres
    environment:
      POSTGRES_USER: bizflow
      POSTGRES_PASSWORD: bizflow
      POSTGRES_DB: bizflow
    ports:
      - "5432:5432"
    volumes:
      - ./infra/db/init:/docker-entrypoint-initdb.d
      - bizflow_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: bizflow-redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: bizflow-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: bizflow
      MINIO_ROOT_PASSWORD: bizflow123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - bizflow_minio:/data

  kafka:
    image: bitnami/kafka:3.7
    container_name: bizflow-kafka
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CFG_NUM_PARTITIONS: 1
    ports:
      - "9092:9092"
    volumes:
      - bizflow_kafka_data:/bitnami/kafka

volumes:
  bizflow_pgdata:
  bizflow_minio:
  bizflow_kafka_data:
