services:
  postgres:
    image: postgres:15-alpine
    container_name: bizflow-postgres
    environment:
      POSTGRES_USER: bizflow
      POSTGRES_PASSWORD: bizflow
      POSTGRES_DB: bizflow
    ports:
      - "5432:5432"
    volumes:
      - ./infra/db/init:/docker-entrypoint-initdb.d
      - bizflow_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: bizflow-redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: bizflow-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: bizflow
      MINIO_ROOT_PASSWORD: bizflow123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - bizflow_minio:/data

  kafka:
    image: apache/kafka:3.9.2
    container_name: bizflow-kafka
    ports:
      - "9092:9092"

volumes:
  bizflow_pgdata:
  bizflow_minio:
