server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/bizflow
    username: bizflow
    password: bizflow
    pool:
      enabled: true
      initial-size: 5
      max-size: 30
      max-idle-time: 30m
      validation-query: SELECT 1
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_GATEWAY:gateway-api}
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.bizflow.shared.events
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.bizflow.shared.events.OutboxEvent
    listener:
      ack-mode: manual_immediate

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"

workflow:
  engine:
    url: http://localhost:8082

bizflow:
  kafka:
    topic: ${KAFKA_TOPIC_EVENTS:events}
