server:
  port: 8082

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/bizflow
    username: bizflow
    password: bizflow
    pool:
      enabled: true
      initial-size: 5
      max-size: 30
      max-idle-time: 30m
      validation-query: SELECT 1
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

bizflow:
  kafka:
    topic: ${KAFKA_TOPIC_EVENTS:events}
    relay:
      enabled: ${KAFKA_OUTBOX_RELAY_ENABLED:true}
      batch-size: ${KAFKA_OUTBOX_RELAY_BATCH_SIZE:20}
      fixed-delay: ${KAFKA_OUTBOX_RELAY_FIXED_DELAY:2000}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
